"""
Skew-t Distribution Fitting
Fits multivariate skew-elliptical t-distribution to financial returns data.

Based on: Azzalini & Capitanio (2003) "Distributions generated by perturbation
of symmetry with emphasis on a multivariate skew t-distribution"
"""

import numpy as np
from scipy.optimize import minimize, differential_evolution
from scipy.special import gamma as gamma_fn
import warnings

warnings.filterwarnings("ignore")


class SkewTFitter:
    """
    Fit multivariate skew-t distribution to data.

    Parametrization (Azzalini & Capitanio):
    - μ: location vector (N,)
    - Σ: scale matrix (N, N)
    - ν: degrees of freedom (scalar > 0)
    - ω: skewness vector (N,)
    """

    def __init__(self, returns_data):
        """
        Args:
            returns_data (np.ndarray): (T, N) array of T observations on N assets
        """
        self.data = returns_data
        self.T, self.N = returns_data.shape
        self.mu = None
        self.sigma = None
        self.nu = None
        self.omega = None

    def fit(self, method="mle", initial_nu=5.0):
        """
        Fit skew-t distribution via MLE.

        Args:
            method (str): 'mle' or 'moment'
            initial_nu (float): Starting point for degrees of freedom

        Returns:
            dict: Fitted parameters {mu, sigma, nu, omega}
        """
        print(
            f"Fitting {self.N}-dimensional skew-t distribution to {self.T} observations..."
        )

        # Moment=based Initialization
        self.mu = np.mean(self.data, axis=0)
        self.sigma = np.cov(self.data.T)
        self.nu = initial_nu
        self.omega = np.zeros(self.N)
        if method == "mle":
            return self._fit_mle()
        elif method == "moment":
            return self._fit_moment_based()
        else:
            raise ValueError(f"Unknown method: {method}.")

    def _fit_mle(self):
        """Maximum Likelihood Estimation for skew-t parameters."""

        def neg_log_likelihood(params):
            """Negative log-likelihood function for minimization."""
            try:
                mu = params[: self.N]
                sigma_vec = params[self.N : self.N + self.N * (self.N + 1) // 2]
                nu = params[self.N + self.N * (self.N + 1) // 2]
                omega = params[self.N + self.N * (self.N + 1) // 2 + 1 :]

                sigma = self._vec_to_matrix(sigma_vec)

                eigvals = np.lingalg.eigvalsh(sigma)
                if np.min(eigvals) < 1e-4:
                    return 1e10

                if nu < 2.1:
                    return 1e10

                ll = self._skew_t_loglik(mu, sigma, nu, omega)
                return -ll

            except:
                return 1e10

        bounds = []
        bounds.extend([(-0.5, 0.5)] * self.N)  # mu bounds
        bounds.extend([(0.001, 1.0)] * self.N)  # sigma diagonal bounds
        bounds.extend([(-0.99, 0.99)] * (self.N * (self.N - 1) // 2))  # sigma bounds
        bounds.append((2.5, 30.0))  # nu bounds
        bounds.extend([(-2.0, 2.0)] * self.N)  # omega bounds

        x0 = self._params_to_vec(self.mu, self.sigma, self.nu, self.omega)

        print("  Optimizing via SLSQP (local optimization)...")
        result = minimize(
            neg_log_likelihood,
            x0,
            method="SLSQP",
            bounds=bounds,
            options={"ftol": 1e-6, "maxiter": 500},
        )

        if result.success:
            params_opt = result.x
        else:
            print("  SLSQP failed, trying global optimization...")
            result = differential_evolution(
                neg_log_likelihood,
                bounds,
                seed=42,
                maxiter=300,
                workers=1,
                updating="deferred",
            )
            params_opt = result.x

        mu = params_opt[: self.N]
        sigma_vec = params_opt[self.N : self.N + self.N * (self.N + 1) // 2]
        nu = params_opt[self.N + self.N * (self.N + 1) // 2]
        omega = params_opt[self.N + self.N * (self.N + 1) // 2 + 1 :]

        sigma = self._vec_to_matrix(sigma_vec)

        self.mu = mu
        self.sigma = sigma
        self.nu = nu
        self.omega = omega

        print(f"  Fit complete. ν={self.nu:.3f}, ||ω||={np.linalg.norm(omega):.3f}")

        return {"mu": self.mu, "sigma": self.sigma, "nu": self.nu, "omega": self.omega}

    def _fit_moment_based(self):
        """Simple moment-based initialization."""

        return {"mu": self.mu, "sigma": self.sigma, "nu": self.nu, "omega": self.omega}

    def _skew_t_loglik(self, mu, sigma, nu, omega):
        """Log-likelihood of skew-t distribution."""

        try:
            sigma_inv = np.linalg.inv(sigma)
            sigma_det = np.linalg.det(sigma)

            if sigma_det <= 0:
                return -np.inf

            X = self.data - mu
            D2 = np.sum(X @ sigma_inv * X, axis=1)

            c = np.sqrt(nu / np.pi) * gamma_fn((nu - 1) / 2) / gamma_fn(nu / 2)
            h = (sigma @ omega) / np.sqrt(1 + omega @ sigma @ omega)

            log_const = (
                (self.N / 2) * np.log(nu / np.pi)
                + self._log_gamma((nu + self.N) / 2)
                - self._log_gamma(nu / 2)
                - 0.5 * np.log(sigma_det)
            )

            log_student = -(nu + self.N) / 2 * np.log(1 + D2 / nu)

            Z = X @ sigma_inv @ h
            skew_adj = np.log(2) + np.log(
                0.5 * (1 + np.tanh(Z * np.sqrt((nu + self.N) / (nu + D2))))
            )

            loglik = np.sum(log_const + log_student + skew_adj)

            return loglik

        except:
            return -np.inf

    def _log_gamma(self, x):
        """Stable computation of log Gamma."""

        return np.log(gamma_fn(x))

    def _params_to_vec(self, mu, sigma, nu, omega):
        """Convert parameters to optimization vector."""

        sigma_lower = sigma[np.tril_indices(self.N)]
        params = np.concatenate([mu, sigma_lower, [nu], omega])
        return params

    def _vec_to_matrix(self, sigma_vec):
        """Reconstruct Sigma from lower triangle vector."""

        sigma = np.zeros((self.N, self.N))
        sigma[np.tril_indices(self.N)] = sigma_vec
        sigma = (sigma + sigma.T) / 2
        return sigma

    def summary(self):
        """Print summary of fitted parameters."""

        print("\n" + "=" * 60)
        print("Skew-t Distribution Fit Summary")
        print("=" * 60)
        print(f"\nLocation (μ):")
        print(self.mu)
        print(f"\nScale matrix (Σ):")
        print(self.sigma)
        print(f"\nDegrees of freedom (ν): {self.nu:.3f}")
        print(f"Skewness (ω):")
        print(self.omega)
        print(f"\nSkewness norm ||ω||: {np.linalg.norm(self.omega):.3f}")
        print("=" * 60 + "\n")
